In [3]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns
sns.set()
print("Aryan Sirdesai");

Aryan Sirdesai


In [4]:
dataset = pd.read_csv('Churn_Modelling.csv', index_col = 'RowNumber')
dataset.head()

CustomerId   Surname  CreditScore Geography  Gender  Age  Tenure  \
RowNumber                                                                     
1            15634602  Hargrave          619    France  Female   42       2   
2            15647311      Hill          608     Spain  Female   41       1   
3            15619304      Onio          502    France  Female   42       8   
4            15701354      Boni          699    France  Female   39       1   
5            15737888  Mitchell          850     Spain  Female   43       2   

             Balance  NumOfProducts  HasCrCard  IsActiveMember  \
RowNumber                                                        
1               0.00              1          1               1   
2           83807.86              1          0               1   
3          159660.80              3          1               0   
4               0.00              2          0               0   
5          125510.82              1          1               1   

           EstimatedSalary  Exited  
RowNumber                           
1                101348.88       1  
2                112542.58       0  
3                113931.57       1  
4                 93826.63       0  
5                 79084.10       0

In [5]:
X_columns = dataset.columns.tolist()[2:12]
Y_columns = dataset.columns.tolist()[-1:]
print(X_columns)
print(Y_columns)

['CreditScore', 'Geography', 'Gender', 'Age', 'Tenure', 'Balance', 'NumOfProducts', 'HasCrCard', 'IsActiveMember', 'EstimatedSalary']
['Exited']


In [6]:
X = dataset[X_columns].values 
Y = dataset[Y_columns].values

In [7]:
from sklearn.preprocessing import LabelEncoder
X_column_transformer = LabelEncoder()
X[:, 1] = X_column_transformer.fit_transform(X[:, 1])

In [8]:
X[:, 2] = X_column_transformer.fit_transform(X[:, 2])

In [9]:
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline

pipeline = Pipeline(
    [
        ('Categorizer', ColumnTransformer(
            [
                ("Gender Label Encoder", OneHotEncoder(categories = 'auto', drop = 'first'), [2]),
                ("Geography Label Encoder", OneHotEncoder(categories = 'auto', drop = 'first'), [1])
            ], 
            remainder = 'passthrough', n_jobs = 1)),
        ('Normalizer', StandardScaler())
    ]
)

In [10]:
X = pipeline.fit_transform(X)

In [11]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size = 0.2, random_state = 0)

In [30]:
# I recommend to upgrade pip 
! pip install --upgrade pip 
# Installing tensorflow 
! pip install tensorflow 

  Using cached pip-23.3.1-py3-none-any.whl (2.1 MB)


ERROR: To modify pip, please run the following command:
C:\Users\aryan\anaconda3\python.exe -m pip install --upgrade pip


In [15]:
import tensorflow as tf 
from tensorflow import keras 

In [16]:
from keras.models import Sequential
from keras.layers import Dense, Dropout

In [17]:
classifier = Sequential()

In [18]:
classifier.add(Dense(6, activation = 'relu', input_shape = (X_train.shape[1], )))
classifier.add(Dropout(rate = 0.1))

In [19]:
classifier.add(Dense(6, activation = 'relu'))
classifier.add(Dropout(rate = 0.1))

In [20]:
classifier.add(Dense(1, activation = 'sigmoid'))

In [21]:
classifier.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 6)                 72        
                                                                 
 dropout (Dropout)           (None, 6)                 0         
                                                                 
 dense_1 (Dense)             (None, 6)                 42        
                                                                 
 dropout_1 (Dropout)         (None, 6)                 0         
                                                                 
 dense_2 (Dense)             (None, 1)                 7         
                                                                 
Total params: 121 (484.00 Byte)
Trainable params: 121 (484.00 Byte)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [22]:
classifier.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

In [23]:
history = classifier.fit(X_train, y_train, batch_size = 32, epochs = 200, validation_split = 0.1, verbose = 2)

Epoch 1/200
225/225 - 3s - loss: 0.6002 - accuracy: 0.7836 - val_loss: 0.5238 - val_accuracy: 0.7950 - 3s/epoch - 14ms/step
Epoch 2/200
225/225 - 1s - loss: 0.4938 - accuracy: 0.8004 - val_loss: 0.4541 - val_accuracy: 0.8062 - 902ms/epoch - 4ms/step
Epoch 3/200
225/225 - 1s - loss: 0.4628 - accuracy: 0.8082 - val_loss: 0.4251 - val_accuracy: 0.8238 - 902ms/epoch - 4ms/step
Epoch 4/200
225/225 - 1s - loss: 0.4476 - accuracy: 0.8146 - val_loss: 0.4117 - val_accuracy: 0.8200 - 918ms/epoch - 4ms/step
Epoch 5/200
225/225 - 1s - loss: 0.4390 - accuracy: 0.8129 - val_loss: 0.4004 - val_accuracy: 0.8363 - 885ms/epoch - 4ms/step
Epoch 6/200
225/225 - 1s - loss: 0.4301 - accuracy: 0.8164 - val_loss: 0.3901 - val_accuracy: 0.8400 - 888ms/epoch - 4ms/step
Epoch 7/200
225/225 - 1s - loss: 0.4244 - accuracy: 0.8215 - val_loss: 0.3832 - val_accuracy: 0.8425 - 834ms/epoch - 4ms/step
Epoch 8/200
225/225 - 1s - loss: 0.4181 - accuracy: 0.8211 - val_loss: 0.3774 - val_accuracy: 0.8413 - 959ms/epoch - 4ms

In [24]:
y_pred = classifier.predict(X_test)
print(y_pred[:5])

63/63 [==============================] - 0s 4ms/step
[[0.28762665]
 [0.22469293]
 [0.19994472]
 [0.06751095]
 [0.10600115]]


In [25]:
y_pred = (y_pred > 0.5).astype(int)
print(y_pred[:5])

[[0]
 [0]
 [0]
 [0]
 [0]]


In [26]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
print(cm)

[[1527   68]
 [ 211  194]]


In [27]:
print(((cm[0][0] + cm[1][1])* 100) / len(y_test), '% of data was classified correctly')

86.05 % of data was classified correctly
