In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns
sns.set()

In [2]:
dataset = pd.read_csv('Churn_Modelling.csv', index_col = 'RowNumber')
dataset.head()

CustomerId   Surname  CreditScore Geography  Gender  Age  Tenure  \
RowNumber                                                                     
1            15634602  Hargrave          619    France  Female   42       2   
2            15647311      Hill          608     Spain  Female   41       1   
3            15619304      Onio          502    France  Female   42       8   
4            15701354      Boni          699    France  Female   39       1   
5            15737888  Mitchell          850     Spain  Female   43       2   

             Balance  NumOfProducts  HasCrCard  IsActiveMember  \
RowNumber                                                        
1               0.00              1          1               1   
2           83807.86              1          0               1   
3          159660.80              3          1               0   
4               0.00              2          0               0   
5          125510.82              1          1               1   

           EstimatedSalary  Exited  
RowNumber                           
1                101348.88       1  
2                112542.58       0  
3                113931.57       1  
4                 93826.63       0  
5                 79084.10       0

In [3]:
X_columns = dataset.columns.tolist()[2:12]
Y_columns = dataset.columns.tolist()[-1:]
print(X_columns)
print(Y_columns)

['CreditScore', 'Geography', 'Gender', 'Age', 'Tenure', 'Balance', 'NumOfProducts', 'HasCrCard', 'IsActiveMember', 'EstimatedSalary']
['Exited']


In [4]:
X = dataset[X_columns].values 
Y = dataset[Y_columns].values

In [5]:
from sklearn.preprocessing import LabelEncoder
X_column_transformer = LabelEncoder()
X[:, 1] = X_column_transformer.fit_transform(X[:, 1])

In [6]:
X[:, 2] = X_column_transformer.fit_transform(X[:, 2])

In [7]:
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline

pipeline = Pipeline(
    [
        ('Categorizer', ColumnTransformer(
            [
                ("Gender Label Encoder", OneHotEncoder(categories = 'auto', drop = 'first'), [2]),
                ("Geography Label Encoder", OneHotEncoder(categories = 'auto', drop = 'first'), [1])
            ], 
            remainder = 'passthrough', n_jobs = 1)),
        ('Normalizer', StandardScaler())
    ]
)

In [8]:
X = pipeline.fit_transform(X)

In [9]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size = 0.2, random_state = 0)

In [12]:
# I recommend to upgrade pip 
! pip install --upgrade pip 
# Installing tensorflow 
! pip install tensorflow 

     ---------------------------------------- 2.1/2.1 MB 14.9 MB/s eta 0:00:00


ERROR: To modify pip, please run the following command:
C:\Users\harsh\anaconda3\python.exe -m pip install --upgrade pip


     -------------------------------------- 284.1/284.1 MB 9.4 MB/s eta 0:00:00
     ---------------------------------------- 57.5/57.5 kB ? eta 0:00:00
     ---------------------------------------- 1.5/1.5 MB 31.4 MB/s eta 0:00:00
     -------------------------------------- 130.2/130.2 kB 8.0 MB/s eta 0:00:00
     ---------------------------------------- 1.7/1.7 MB 106.2 MB/s eta 0:00:00
     ---------------------------------------- 3.7/3.7 MB 46.8 MB/s eta 0:00:00
     ---------------------------------------- 938.6/938.6 kB ? eta 0:00:00
     ------------------------------------- 440.7/440.7 kB 26.9 MB/s eta 0:00:00
     ---------------------------------------- 65.5/65.5 kB 3.5 MB/s eta 0:00:00
     --------------------------------------- 24.4/24.4 MB 25.1 MB/s eta 0:00:00
     ---------------------------------------- 5.5/5.5 MB 35.2 MB/s eta 0:00:00
     ------------------------------------- 430.5/430.5 kB 26.3 MB/s eta 0:00:00
     ---------------------------------------- 182.3/182

In [13]:
import tensorflow as tf 
from tensorflow import keras 

In [14]:
from keras.models import Sequential
from keras.layers import Dense, Dropout

In [15]:
classifier = Sequential()

In [16]:
classifier.add(Dense(6, activation = 'relu', input_shape = (X_train.shape[1], )))
classifier.add(Dropout(rate = 0.1))

In [17]:
classifier.add(Dense(6, activation = 'relu'))
classifier.add(Dropout(rate = 0.1))

In [18]:
classifier.add(Dense(1, activation = 'sigmoid'))

In [19]:
classifier.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 6)                 72        
                                                                 
 dropout (Dropout)           (None, 6)                 0         
                                                                 
 dense_1 (Dense)             (None, 6)                 42        
                                                                 
 dropout_1 (Dropout)         (None, 6)                 0         
                                                                 
 dense_2 (Dense)             (None, 1)                 7         
                                                                 
Total params: 121 (484.00 Byte)
Trainable params: 121 (484.00 Byte)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [20]:
classifier.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

In [21]:
history = classifier.fit(X_train, y_train, batch_size = 32, epochs = 200, validation_split = 0.1, verbose = 2)

Epoch 1/200
225/225 - 1s - loss: 0.5434 - accuracy: 0.7946 - val_loss: 0.4984 - val_accuracy: 0.7950 - 1s/epoch - 5ms/step
Epoch 2/200
225/225 - 0s - loss: 0.4974 - accuracy: 0.7961 - val_loss: 0.4751 - val_accuracy: 0.7950 - 309ms/epoch - 1ms/step
Epoch 3/200
225/225 - 0s - loss: 0.4800 - accuracy: 0.7961 - val_loss: 0.4606 - val_accuracy: 0.7950 - 378ms/epoch - 2ms/step
Epoch 4/200
225/225 - 0s - loss: 0.4733 - accuracy: 0.7961 - val_loss: 0.4506 - val_accuracy: 0.7950 - 319ms/epoch - 1ms/step
Epoch 5/200
225/225 - 0s - loss: 0.4638 - accuracy: 0.7961 - val_loss: 0.4431 - val_accuracy: 0.7950 - 312ms/epoch - 1ms/step
Epoch 6/200
225/225 - 0s - loss: 0.4583 - accuracy: 0.7961 - val_loss: 0.4364 - val_accuracy: 0.7950 - 291ms/epoch - 1ms/step
Epoch 7/200
225/225 - 0s - loss: 0.4509 - accuracy: 0.7961 - val_loss: 0.4308 - val_accuracy: 0.7950 - 282ms/epoch - 1ms/step
Epoch 8/200
225/225 - 0s - loss: 0.4476 - accuracy: 0.7961 - val_loss: 0.4258 - val_accuracy: 0.7950 - 314ms/epoch - 1ms/

Epoch 66/200
225/225 - 0s - loss: 0.3774 - accuracy: 0.8499 - val_loss: 0.3356 - val_accuracy: 0.8687 - 298ms/epoch - 1ms/step
Epoch 67/200
225/225 - 0s - loss: 0.3830 - accuracy: 0.8489 - val_loss: 0.3363 - val_accuracy: 0.8662 - 397ms/epoch - 2ms/step
Epoch 68/200
225/225 - 0s - loss: 0.3791 - accuracy: 0.8531 - val_loss: 0.3353 - val_accuracy: 0.8675 - 297ms/epoch - 1ms/step
Epoch 69/200
225/225 - 0s - loss: 0.3794 - accuracy: 0.8507 - val_loss: 0.3360 - val_accuracy: 0.8687 - 384ms/epoch - 2ms/step
Epoch 70/200
225/225 - 0s - loss: 0.3768 - accuracy: 0.8515 - val_loss: 0.3358 - val_accuracy: 0.8687 - 306ms/epoch - 1ms/step
Epoch 71/200
225/225 - 0s - loss: 0.3787 - accuracy: 0.8496 - val_loss: 0.3357 - val_accuracy: 0.8687 - 299ms/epoch - 1ms/step
Epoch 72/200
225/225 - 0s - loss: 0.3801 - accuracy: 0.8483 - val_loss: 0.3376 - val_accuracy: 0.8687 - 324ms/epoch - 1ms/step
Epoch 73/200
225/225 - 0s - loss: 0.3822 - accuracy: 0.8487 - val_loss: 0.3393 - val_accuracy: 0.8687 - 429ms/e

Epoch 131/200
225/225 - 0s - loss: 0.3786 - accuracy: 0.8512 - val_loss: 0.3353 - val_accuracy: 0.8712 - 330ms/epoch - 1ms/step
Epoch 132/200
225/225 - 0s - loss: 0.3750 - accuracy: 0.8511 - val_loss: 0.3352 - val_accuracy: 0.8687 - 401ms/epoch - 2ms/step
Epoch 133/200
225/225 - 0s - loss: 0.3748 - accuracy: 0.8496 - val_loss: 0.3342 - val_accuracy: 0.8687 - 384ms/epoch - 2ms/step
Epoch 134/200
225/225 - 0s - loss: 0.3754 - accuracy: 0.8528 - val_loss: 0.3372 - val_accuracy: 0.8737 - 364ms/epoch - 2ms/step
Epoch 135/200
225/225 - 0s - loss: 0.3800 - accuracy: 0.8496 - val_loss: 0.3358 - val_accuracy: 0.8737 - 347ms/epoch - 2ms/step
Epoch 136/200
225/225 - 0s - loss: 0.3765 - accuracy: 0.8478 - val_loss: 0.3329 - val_accuracy: 0.8650 - 325ms/epoch - 1ms/step
Epoch 137/200
225/225 - 0s - loss: 0.3804 - accuracy: 0.8512 - val_loss: 0.3354 - val_accuracy: 0.8725 - 323ms/epoch - 1ms/step
Epoch 138/200
225/225 - 0s - loss: 0.3762 - accuracy: 0.8492 - val_loss: 0.3346 - val_accuracy: 0.8687 -

225/225 - 0s - loss: 0.3775 - accuracy: 0.8483 - val_loss: 0.3293 - val_accuracy: 0.8725 - 368ms/epoch - 2ms/step
Epoch 196/200
225/225 - 0s - loss: 0.3758 - accuracy: 0.8515 - val_loss: 0.3309 - val_accuracy: 0.8750 - 385ms/epoch - 2ms/step
Epoch 197/200
225/225 - 0s - loss: 0.3790 - accuracy: 0.8497 - val_loss: 0.3324 - val_accuracy: 0.8737 - 423ms/epoch - 2ms/step
Epoch 198/200
225/225 - 0s - loss: 0.3779 - accuracy: 0.8490 - val_loss: 0.3349 - val_accuracy: 0.8700 - 384ms/epoch - 2ms/step
Epoch 199/200
225/225 - 0s - loss: 0.3772 - accuracy: 0.8451 - val_loss: 0.3308 - val_accuracy: 0.8737 - 354ms/epoch - 2ms/step
Epoch 200/200
225/225 - 0s - loss: 0.3771 - accuracy: 0.8487 - val_loss: 0.3345 - val_accuracy: 0.8700 - 358ms/epoch - 2ms/step


In [23]:
y_pred = classifier.predict(X_test)
print(y_pred[:5])

63/63 [==============================] - 0s 2ms/step
[[0.39968973]
 [0.4173336 ]
 [0.29057747]
 [0.11842419]
 [0.11836001]]


In [24]:
y_pred = (y_pred > 0.5).astype(int)
print(y_pred[:5])

[[0]
 [0]
 [0]
 [0]
 [0]]


In [25]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
print(cm)

[[1511   84]
 [ 186  219]]


In [26]:
print(((cm[0][0] + cm[1][1])* 100) / len(y_test), '% of data was classified correctly')

86.5 % of data was classified correctly
